[program:ticket_printer]
command=/home/leonvic13/Documents/ticket_thermaBaseLeonv2/ticket_printer/run.sh web
directory=/home/leonvic13/Documents/ticket_thermaBaseLeonv2/ticket_printer
user=leonvic13
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stopsignal=TERM
stdout_logfile=/home/leonvic13/Documents/ticket_thermaBaseLeonv2/ticket_printer/supervisor_stdout.log
stderr_logfile=/home/leonvic13/Documents/ticket_thermaBaseLeonv2/ticket_printer/supervisor_stderr.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=PATH="/home/leonvic13/Documents/ticket_thermaBaseLeonv2/ticket_printer/venv/bin:%(ENV_PATH)s"
